### PR TITLE
Draft | Rewrite

### PR DESCRIPTION
**Pull request by JonasPardon**
### Todo
- [x] Find static calls (`Class::dispatch()`)
- [x] Find method calls (`$instance->dispatch()`)
- [x] Resolve classes from variables (to support `Class::dispatch($eventOrJob)` -> what class is `$eventOrJob`)
- [x] Extract dispatched classes from a subject class (class X is related to class Y & Z because Y & Z are used/dispatched from X)
- [ ] #10
- [ ] #11 
- [ ] #12

### CODE REVIEW

**Comment by joelvh** [comment]
@JonasPardon does the parsing work with `event(...)` and `dispatch(...)` helpers?

**Comment by JonasPardon** [comment]
@joelvh currently not, but that's an easy one to add. I will make sure to include it.

I sometimes overlook that one as I don't ever use that syntax myself 😄

**Comment by JonasPardon** [comment]
@joelvh any chance you could provide me with some sample classes of your use case with the `event()` and `dispatch()` helpers?

It would be helpful to have some barebones examples. Feel free to sanitize/obfuscate them if there's any sensitive code in there you don't want exposed. If you don't mind that I can also santizie/obfuscate them when I add them to the test cases.

The more examples you're willing to provide, the more use cases I can cover in tests.

An example of what I've done with a use case I came across in my work codebase: https://github.com/JonasPardon/laravel-event-visualizer/blob/91cafdb4d758eb944f225b8a9237754925caddb8/tests/Unit/CodeParser/MethodCallsParsingTest.php#L90-L129

**Comment by JonasPardon** [comment]
> @JonasPardon does the parsing work with `event(...)` and `dispatch(...)` helpers?

@joelvh I've tagged a new `v0.3.0` release that should now support the `event(...)` and `dispatch(...)`, if you have some time please do try it out and let me know if you encounter any hiccups!

**Comment by joelvh** [comment]
hey @JonasPardon sorry for the delayed response. Glad to hear you have an approach to handling those helpers! I'll take a look -- do you still want examples?

**Comment by joelvh** [comment]
I'll give this a spin and maybe is best for me to show examples that fail. thanks!

**Comment by JonasPardon** [comment]
@joelvh no worries! Examples are not very necessary, but I would love some examples of any failures you find.

**Pull request merged**
